version: 2.1

jobs:
  "test":
    parameters:
      v:
        type: string
        default: "latest"
      latest:
        type: boolean
        default: false
      golint:
        type: boolean
        default: true
      modules:
        type: boolean
        default: true
      goproxy:
        type: string
        default: ""
    docker:
      - image: "circleci/golang:<< parameters.v >>"
    working_directory: /go/src/github.com/elithrar/admission-control
    environment:
      GO111MODULE: "on"
      GOPROXY: "<< parameters.goproxy >>"
    steps:
      - checkout
      - run:
          name: "Print the Go version"
          command: >
            go version
      - run:
          name: "Fetch dependencies"
          command: >
            if [[ << parameters.modules >> = true ]]; then
              go mod download
              export GO111MODULE=on
            else
              go get -v ./...
            fi
      # Only run gofmt, vet & lint against the latest Go version
      - run:
          name: "Run golint"
          command: >
            if [ << parameters.latest >> = true ] && [ << parameters.golint >> = true ]; then
              go get -u golang.org/x/lint/golint
              golint ./...
            fi
      - run:
          name: "Run gofmt"
          command: >
            if [[ << parameters.latest >> = true ]]; then
              diff -u <(echo -n) <(gofmt -d -e .)
            fi
      - run:
          name: "Run go vet"
          command: >
            if [[ << parameters.latest >> = true ]]; then
              go vet -v ./...
            fi
      - run:
          name: "Run go test (+ race detector)"
          command: >
            go test -v -race ./...

  "build-container":
    docker:
      - image: docker:18
    working_directory: /go/src/github.com/elithrar/admission-control
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Print the Docker version"
          command: >
            docker version
      - run:
          name: "Build the container image"
          command: >
            docker build -t elithrar/admissiond-example .

workflows:
  build:
    jobs:
      - test:
          name: "latest"
          v: "latest"
          latest: true
      - test:
          name: "v1.15"
          v: "1.15"
      - test:
          name: "v1.14"
          v: "1.14"
      - test:
          name: "v1.13"
          v: "1.13"
      - "build-container"
